name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:    
      - name: Check out source code
        uses: actions/checkout@v4  

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Instalar Visual Studio Build Tools
      - name: Install Visual Studio Build Tools
        run: |
          choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.MSBuild" --confirm

      # Verificar a instalação do MSBuild
      - name: Verify MSBuild
        run: |
          msbuild -version
          where msbuild

      # Etapa do Fortify
      - name: Run FoD SAST Scan
        uses: fortify/github-action/fod-sast-scan@v1
        env:
          FOD_URL: https://trial.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          FOD_RELEASE: dotnet:MyRelease
